login:
  template: 'login'
  controller: 'core\login\LoginController::login'

home:
  template: 'dashboard'
  controller: 'core\dashboard\DashboardController::build'

playback:
  template: 'playback'
  controller: 'core\playback\PlaybackController::build'

config:
  template: 'config'
  controller: 'core\config\ConfigController::build'

logout:
  controller: 'core\login\LoginController::logout'

event.flag:
  controller: 'core\playback\EventFlagController::flagEvent'

alarm.enable:
  controller: 'core\alarm\AlarmController::enableAlarm'

alarm.disable:
  controller: 'core\alarm\AlarmController::disableAlarm'

events.new:
  controller: 'core\playback\PlaybackController::getNewEvents'